<?php
declare(strict_types=1);

namespace Foundry\Tests\Unit;

use Foundry\CLI\Commands\GenerateFeatureCommand;
use Foundry\CLI\Commands\GenerateIndexesCommand;
use Foundry\CLI\Commands\GenerateScaffoldCommand;
use Foundry\CLI\Commands\GeneratePlatformCommand;
use Foundry\CLI\Commands\GenerateIntegrationCommand;
use Foundry\CLI\Commands\GraphVisualizeCommand;
use Foundry\CLI\Commands\ImpactCommand;
use Foundry\CLI\Commands\InitAppCommand;
use Foundry\CLI\Commands\InspectApiCommand;
use Foundry\CLI\Commands\InspectGraphCommand;
use Foundry\CLI\Commands\InspectPlatformCommand;
use Foundry\CLI\Commands\InspectFeatureCommand;
use Foundry\CLI\Commands\InspectNotificationCommand;
use Foundry\CLI\Commands\InspectResourceCommand;
use Foundry\CLI\Commands\InspectRouteCommand;
use Foundry\CLI\Commands\MigrateDefinitionsCommand;
use Foundry\CLI\Commands\DoctorCommand;
use Foundry\CLI\Commands\ExportGraphCommand;
use Foundry\CLI\Commands\ExportOpenApiCommand;
use Foundry\CLI\Commands\PreviewNotificationCommand;
use Foundry\CLI\Commands\PromptCommand;
use Foundry\CLI\Commands\QueueWorkCommand;
use Foundry\CLI\Commands\ScheduleRunCommand;
use Foundry\CLI\Commands\ServeCommand;
use Foundry\CLI\Commands\CodemodRunCommand;
use Foundry\CLI\Commands\CompileGraphCommand;
use Foundry\CLI\Commands\VerifyCompatibilityCommand;
use Foundry\CLI\Commands\VerifyGraphCommand;
use Foundry\CLI\Commands\VerifyPipelineCommand;
use Foundry\CLI\Commands\VerifyContractsCommand;
use Foundry\CLI\Commands\VerifyFeatureCommand;
use Foundry\CLI\Commands\VerifyIntegrationCommand;
use Foundry\CLI\Commands\VerifyPlatformCommand;
use Foundry\CLI\Commands\VerifyResourceCommand;
use PHPUnit\Framework\TestCase;

final class CLICommandMatchesTest extends TestCase
{
    public function test_matches_methods_cover_all_commands(): void
    {
        $this->assertTrue((new InspectFeatureCommand())->matches(['inspect', 'feature', 'x']));
        $this->assertTrue((new InspectNotificationCommand())->matches(['inspect', 'notification', 'welcome_email']));
        $this->assertTrue((new InspectApiCommand())->matches(['inspect', 'api', 'posts']));
        $this->assertTrue((new InspectResourceCommand())->matches(['inspect', 'resource', 'posts']));
        $this->assertFalse((new InspectFeatureCommand())->matches(['other']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'graph']));
        $this->assertTrue((new InspectGraphCommand())->matches(['graph', 'inspect']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'impact', '--file=app/features/x/feature.yaml']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'dependencies', 'feature:x']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'extension', 'core']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'packs']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'pack', 'core.foundation']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'compatibility']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'definition-format', 'feature_manifest']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'api-surface']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'pipeline']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'execution-plan', 'publish_post']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'guards', 'publish_post']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'interceptors', '--stage=auth']));
        $this->assertFalse((new InspectGraphCommand())->matches(['inspect', 'dependencies', 'x']));

        $this->assertTrue((new InspectRouteCommand())->matches(['inspect', 'route', 'GET', '/']));
        $this->assertTrue((new InitAppCommand())->matches(['init', 'app', './my-app']));
        $this->assertTrue((new InitAppCommand())->matches(['new', './my-app']));
        $this->assertTrue((new GenerateFeatureCommand())->matches(['generate', 'feature', 'x.yaml']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'starter', 'api']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'resource', 'posts', '--definition=definitions/posts.resource.yaml']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'admin-resource', 'posts']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'uploads', 'avatar']));
        $this->assertTrue((new GenerateIntegrationCommand())->matches(['generate', 'notification', 'welcome_email']));
        $this->assertTrue((new GenerateIntegrationCommand())->matches(['generate', 'api-resource', 'posts', '--definition=definitions/posts.api-resource.yaml']));
        $this->assertTrue((new GenerateIntegrationCommand())->matches(['generate', 'docs', '--format=markdown']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'billing', 'stripe']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'workflow', 'posts', '--definition=definitions/posts.workflow.yaml']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'orchestration', 'process_doc', '--definition=definitions/process_doc.orchestration.yaml']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'search-index', 'posts', '--definition=definitions/posts.search.yaml']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'stream', 'job-progress']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'locale', 'fr']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'roles']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'policy', 'posts']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'inspect-ui']));
        $this->assertTrue((new GenerateFeatureCommand())->matches(['generate', 'tests', '--all-missing']));
        $this->assertTrue((new GenerateIndexesCommand())->matches(['generate', 'indexes']));
        $this->assertTrue((new ExportGraphCommand())->matches(['export', 'graph', '--format=json']));
        $this->assertTrue((new ExportOpenApiCommand())->matches(['export', 'openapi', '--format=json']));
        $this->assertTrue((new PreviewNotificationCommand())->matches(['preview', 'notification', 'welcome_email']));
        $this->assertTrue((new CompileGraphCommand())->matches(['compile', 'graph']));
        $this->assertTrue((new DoctorCommand())->matches(['doctor']));
        $this->assertTrue((new GraphVisualizeCommand())->matches(['graph', 'visualize']));
        $this->assertTrue((new PromptCommand())->matches(['prompt', 'add', 'feature']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'billing']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'workflow', 'posts']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'orchestration', 'process_doc']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'search', 'posts']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'streams']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'locales']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'roles']));
        $this->assertTrue((new VerifyFeatureCommand())->matches(['verify', 'feature', 'x']));
        $this->assertTrue((new VerifyResourceCommand())->matches(['verify', 'resource', 'posts']));
        $this->assertTrue((new VerifyIntegrationCommand())->matches(['verify', 'notifications']));
        $this->assertTrue((new VerifyIntegrationCommand())->matches(['verify', 'api']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'billing']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'workflows']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'orchestrations']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'search']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'streams']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'locales']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'policies']));
        $this->assertTrue((new VerifyContractsCommand())->matches(['verify', 'contracts']));
        $this->assertTrue((new VerifyGraphCommand())->matches(['verify', 'graph']));
        $this->assertTrue((new VerifyPipelineCommand())->matches(['verify', 'pipeline']));
        $this->assertTrue((new VerifyCompatibilityCommand())->matches(['verify', 'extensions']));
        $this->assertTrue((new VerifyCompatibilityCommand())->matches(['verify', 'compatibility']));
        $this->assertTrue((new ServeCommand())->matches(['serve']));
        $this->assertTrue((new QueueWorkCommand())->matches(['queue:work']));
        $this->assertTrue((new ScheduleRunCommand())->matches(['schedule:run']));
        $this->assertTrue((new ImpactCommand())->matches(['affected-files', 'x']));
        $this->assertTrue((new MigrateDefinitionsCommand())->matches(['migrate', 'definitions', '--dry-run']));
        $this->assertTrue((new CodemodRunCommand())->matches(['codemod', 'run', 'feature-manifest-v1-to-v2', '--dry-run']));
    }
}
