<?php

declare(strict_types=1);

namespace Foundry\Tests\Unit;

use Foundry\CLI\Commands\CacheClearCommand;
use Foundry\CLI\Commands\CacheInspectCommand;
use Foundry\CLI\Commands\CodemodRunCommand;
use Foundry\CLI\Commands\CompileGraphCommand;
use Foundry\CLI\Commands\ContextCheckAlignmentCommand;
use Foundry\CLI\Commands\ContextBootstrapCommand;
use Foundry\CLI\Commands\ContextRecoverCommand;
use Foundry\CLI\Commands\ContextRepairCommand;
use Foundry\CLI\Commands\DeepDoctorCommand;
use Foundry\CLI\Commands\DiffCommand;
use Foundry\CLI\Commands\DoctorCommand;
use Foundry\CLI\Commands\ExamplesCommand;
use Foundry\CLI\Commands\ExplainCommand;
use Foundry\CLI\Commands\ExportGraphCommand;
use Foundry\CLI\Commands\ExportOpenApiCommand;
use Foundry\CLI\Commands\FeaturesCommand;
use Foundry\CLI\Commands\FeatureSystemCommand;
use Foundry\CLI\Commands\GenerateCommand as PromptGenerateCommand;
use Foundry\CLI\Commands\GenerateFeatureCommand;
use Foundry\CLI\Commands\GenerateIndexesCommand;
use Foundry\CLI\Commands\GenerateIntegrationCommand;
use Foundry\CLI\Commands\GenerateMetricsCommand;
use Foundry\CLI\Commands\GeneratePlatformCommand;
use Foundry\CLI\Commands\GenerateScaffoldCommand;
use Foundry\CLI\Commands\GraphVisualizeCommand;
use Foundry\CLI\Commands\HistoricalSpecsContextCommand;
use Foundry\CLI\Commands\HistoricalSpecsEvidenceCommand;
use Foundry\CLI\Commands\HistoricalSpecsExtractCommand;
use Foundry\CLI\Commands\HistoricalSpecsImportCommand;
use Foundry\CLI\Commands\HistoricalSpecsReconstructCommand;
use Foundry\CLI\Commands\HistoryCommand;
use Foundry\CLI\Commands\ImpactCommand;
use Foundry\CLI\Commands\ImplementFeatureCommand;
use Foundry\CLI\Commands\ImplementSpecCommand;
use Foundry\CLI\Commands\InitAppCommand;
use Foundry\CLI\Commands\InitCommand;
use Foundry\CLI\Commands\InspectApiCommand;
use Foundry\CLI\Commands\InspectContextCommand;
use Foundry\CLI\Commands\InspectFeatureCommand;
use Foundry\CLI\Commands\InspectGraphCommand;
use Foundry\CLI\Commands\InspectNotificationCommand;
use Foundry\CLI\Commands\InspectPlatformCommand;
use Foundry\CLI\Commands\InspectResourceCommand;
use Foundry\CLI\Commands\InspectRouteCommand;
use Foundry\CLI\Commands\InspectStateStoreCommand;
use Foundry\CLI\Commands\LicenseCommand;
use Foundry\CLI\Commands\MarketplaceCommand;
use Foundry\CLI\Commands\MarketplaceIdentityCommand;
use Foundry\CLI\Commands\MigrateDefinitionsCommand;
use Foundry\CLI\Commands\ObserveCommand;
use Foundry\CLI\Commands\PackCommand;
use Foundry\CLI\Commands\PlanFeatureCommand;
use Foundry\CLI\Commands\PlanListCommand;
use Foundry\CLI\Commands\PlanReplayCommand;
use Foundry\CLI\Commands\PlanShowCommand;
use Foundry\CLI\Commands\PlanUndoCommand;
use Foundry\CLI\Commands\PreCanonicalImportCommand;
use Foundry\CLI\Commands\PreviewNotificationCommand;
use Foundry\CLI\Commands\PromptCommand;
use Foundry\CLI\Commands\QueueWorkCommand;
use Foundry\CLI\Commands\RegressionsCommand;
use Foundry\CLI\Commands\ScheduleRunCommand;
use Foundry\CLI\Commands\ServeCommand;
use Foundry\CLI\Commands\SpecLogEntryCommand;
use Foundry\CLI\Commands\SpecNewCommand;
use Foundry\CLI\Commands\SpecPlanCommand;
use Foundry\CLI\Commands\SpecPromoteCommand;
use Foundry\CLI\Commands\SpecValidateCommand;
use Foundry\CLI\Commands\TestFeatureCommand;
use Foundry\CLI\Commands\TraceCommand;
use Foundry\CLI\Commands\UpgradeCheckCommand;
use Foundry\CLI\Commands\VerifyCompatibilityCommand;
use Foundry\CLI\Commands\VerifyContextCommand;
use Foundry\CLI\Commands\VerifyDoneCommand;
use Foundry\CLI\Commands\VerifyFeatureWorkCommand;
use Foundry\CLI\Commands\VerifyContractsCommand;
use Foundry\CLI\Commands\VerifyFeatureCommand;
use Foundry\CLI\Commands\VerifyFeaturesCommand;
use Foundry\CLI\Commands\VerifyGraphCommand;
use Foundry\CLI\Commands\VerifyArchitectureCommand;
use Foundry\CLI\Commands\VerifyIntegrationCommand;
use Foundry\CLI\Commands\VerifyPipelineCommand;
use Foundry\CLI\Commands\VerifyPlatformCommand;
use Foundry\CLI\Commands\VerifyResourceCommand;
use Foundry\CLI\Commands\VerifyStateStoreCommand;
use PHPUnit\Framework\TestCase;

final class CLICommandMatchesTest extends TestCase
{
    public function test_matches_methods_cover_all_commands(): void
    {
        $this->assertTrue((new InspectFeatureCommand())->matches(['inspect', 'feature', 'x']));
        $this->assertTrue((new InspectContextCommand())->matches(['inspect', 'context', 'x']));
        $this->assertTrue((new InspectStateStoreCommand())->matches(['inspect', 'state-store']));
        $this->assertTrue((new InspectNotificationCommand())->matches(['inspect', 'notification', 'welcome_email']));
        $this->assertTrue((new InspectApiCommand())->matches(['inspect', 'api', 'posts']));
        $this->assertTrue((new InspectResourceCommand())->matches(['inspect', 'resource', 'posts']));
        $this->assertFalse((new InspectFeatureCommand())->matches(['other']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'graph']));
        $this->assertTrue((new InspectGraphCommand())->matches(['graph', 'inspect']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'impact', '--file=app/features/x/feature.yaml']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'dependencies', 'feature:x']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'extension', 'core']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'packs']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'pack', 'core.foundation']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'compatibility']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'definition-format', 'feature_manifest']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'graph-spec']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'node-types']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'edge-types']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'subgraph', 'publish_post']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'graph-integrity']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'api-surface']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'cli-surface']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'pipeline']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'execution-plan', 'publish_post']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'guards', 'publish_post']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'interceptors', '--stage=auth']));
        $this->assertTrue((new InspectGraphCommand())->matches(['inspect', 'dependencies', 'x']));

        $this->assertTrue((new InspectRouteCommand())->matches(['inspect', 'route', 'GET', '/']));
        $this->assertTrue((new InitCommand())->matches(['init']));
        $this->assertTrue((new InitAppCommand())->matches(['init', 'app', './my-app']));
        $this->assertTrue((new InitAppCommand())->matches(['new', './my-app']));
        $this->assertTrue((new ExamplesCommand())->matches(['examples:list']));
        $this->assertTrue((new ExamplesCommand())->matches(['examples:load', 'blog']));
        $this->assertTrue((new GenerateFeatureCommand())->matches(['generate', 'feature', 'x.yaml']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'starter', 'api']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'resource', 'posts', '--definition=definitions/posts.resource.yaml']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'admin-resource', 'posts']));
        $this->assertTrue((new GenerateScaffoldCommand())->matches(['generate', 'uploads', 'avatar']));
        $this->assertTrue((new GenerateIntegrationCommand())->matches(['generate', 'notification', 'welcome_email']));
        $this->assertTrue((new GenerateIntegrationCommand())->matches(['generate', 'api-resource', 'posts', '--definition=definitions/posts.api-resource.yaml']));
        $this->assertTrue((new GenerateIntegrationCommand())->matches(['generate', 'docs', '--format=markdown']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'billing', 'stripe']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'workflow', 'posts', '--definition=definitions/posts.workflow.yaml']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'orchestration', 'process_doc', '--definition=definitions/process_doc.orchestration.yaml']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'search-index', 'posts', '--definition=definitions/posts.search.yaml']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'stream', 'job-progress']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'locale', 'fr']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'roles']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'policy', 'posts']));
        $this->assertTrue((new GeneratePlatformCommand())->matches(['generate', 'inspect-ui']));
        $this->assertTrue((new GenerateFeatureCommand())->matches(['generate', 'tests', '--all-missing']));
        $this->assertTrue((new GenerateIndexesCommand())->matches(['generate', 'indexes']));
        $this->assertTrue((new ExportGraphCommand())->matches(['export', 'graph', '--format=json']));
        $this->assertTrue((new ExportOpenApiCommand())->matches(['export', 'openapi', '--format=json']));
        $this->assertTrue((new PreviewNotificationCommand())->matches(['preview', 'notification', 'welcome_email']));
        $this->assertTrue((new CompileGraphCommand())->matches(['compile', 'graph']));
        $this->assertTrue((new ContextCheckAlignmentCommand())->matches(['context', 'check-alignment', '--feature=event-bus']));
        $this->assertTrue((new ContextBootstrapCommand())->matches(['context', 'bootstrap', 'event-bus']));
        $this->assertTrue((new ContextRecoverCommand())->matches(['context', 'recover', 'event-bus']));
        $this->assertTrue((new ContextRepairCommand())->matches(['context', 'repair', '--feature=event-bus']));
        $this->assertTrue((new ImplementFeatureCommand())->matches(['implement', 'feature', 'event-bus']));
        $this->assertTrue((new ImplementSpecCommand())->matches(['implement', 'spec', 'event-bus/001-initial']));
        $this->assertTrue((new PlanFeatureCommand())->matches(['plan', 'feature', 'event-bus']));
        $this->assertTrue((new PlanListCommand())->matches(['plan:list']));
        $this->assertTrue((new PlanReplayCommand())->matches(['plan:replay', '123e4567-e89b-12d3-a456-426614174000']));
        $this->assertTrue((new PlanShowCommand())->matches(['plan:show', '123e4567-e89b-12d3-a456-426614174000']));
        $this->assertTrue((new PlanUndoCommand())->matches(['plan:undo', '123e4567-e89b-12d3-a456-426614174000']));
        $this->assertTrue((new SpecNewCommand())->matches(['spec:new', 'execution-spec-system', 'add-cli-command']));
        $this->assertTrue((new SpecPlanCommand())->matches(['spec:plan', 'execution-spec-system', '008']));
        $this->assertTrue((new SpecPromoteCommand())->matches(['spec:promote', 'execution-spec-system', '008']));
        $this->assertTrue((new SpecLogEntryCommand())->matches(['spec:log-entry', 'execution-spec-system', '004']));
        $this->assertTrue((new SpecValidateCommand())->matches(['spec:validate']));
        $this->assertTrue((new CacheInspectCommand())->matches(['cache', 'inspect']));
        $this->assertTrue((new CacheClearCommand())->matches(['cache', 'clear']));
        $this->assertTrue((new DeepDoctorCommand())->matches(['doctor', '--deep']));
        $this->assertTrue((new DoctorCommand())->matches(['doctor']));
        $this->assertTrue((new DoctorCommand())->matches(['doctor', '--cli']));
        $this->assertTrue((new DoctorCommand())->matches(['doctor', '--deep']));
        $this->assertTrue((new DoctorCommand())->matches(['doctor', '--ready']));
        $this->assertTrue((new DoctorCommand())->matches(['doctor', '--graph']));
        $this->assertTrue((new DoctorCommand())->matches(['doctor', '--quality']));
        $this->assertTrue((new ExplainCommand())->matches(['explain', 'publish_post']));
        $this->assertTrue((new DiffCommand())->matches(['diff']));
        $this->assertTrue((new TraceCommand())->matches(['trace', 'publish_post']));
        $this->assertTrue((new ObserveCommand())->matches(['observe:trace', 'publish_post']));
        $this->assertTrue((new ObserveCommand())->matches(['observe:profile']));
        $this->assertTrue((new ObserveCommand())->matches(['observe:compare', 'trace-a', 'trace-b']));
        $this->assertTrue((new HistoryCommand())->matches(['history']));
        $this->assertTrue((new HistoricalSpecsContextCommand())->matches(['historical-specs:context', '--dry-run']));
        $this->assertTrue((new HistoricalSpecsEvidenceCommand())->matches(['historical-specs:evidence', '--dry-run']));
        $this->assertTrue((new HistoricalSpecsExtractCommand())->matches(['historical-specs:extract', '--dry-run']));
        $this->assertTrue((new HistoricalSpecsImportCommand())->matches(['historical-specs:import', '--dry-run']));
        $this->assertTrue((new HistoricalSpecsReconstructCommand())->matches(['historical-specs:reconstruct', '--dry-run']));
        $this->assertTrue((new PreCanonicalImportCommand())->matches(['precanonical:import', '--source=_import/precanonical/marked-archive.md']));
        $this->assertTrue((new RegressionsCommand())->matches(['regressions']));
        $this->assertTrue((new LicenseCommand())->matches(['license', 'activate', 'key']));
        $this->assertTrue((new MarketplaceIdentityCommand())->matches(['login', '--user=demo', '--token=abc']));
        $this->assertTrue((new MarketplaceIdentityCommand())->matches(['logout']));
        $this->assertTrue((new MarketplaceIdentityCommand())->matches(['whoami']));
        $this->assertTrue((new MarketplaceIdentityCommand())->matches(['entitlements']));
        $this->assertTrue((new FeaturesCommand())->matches(['features']));
        $this->assertTrue((new FeatureSystemCommand())->matches(['feature:list']));
        $this->assertTrue((new FeatureSystemCommand())->matches(['feature:inspect', 'event-system']));
        $this->assertTrue((new FeatureSystemCommand())->matches(['feature:map']));
        $this->assertTrue((new PackCommand())->matches(['pack', 'install', '/tmp/pack']));
        $this->assertTrue((new PackCommand())->matches(['pack', 'purchase', 'vendor/premium-pack']));
        $this->assertTrue((new PackCommand())->matches(['pack', 'search', 'blog']));
        $this->assertTrue((new PackCommand())->matches(['pack', 'remove', 'foundry/blog']));
        $this->assertTrue((new PackCommand())->matches(['pack', 'list']));
        $this->assertTrue((new PackCommand())->matches(['pack', 'info', 'foundry/blog']));
        $this->assertTrue((new PromptGenerateCommand())->matches(['generate', 'add', 'bookmark', 'support']));
        $this->assertTrue((new PromptGenerateCommand())->matches(['generate', '--workflow=generate-workflow.json']));
        $this->assertTrue((new PromptGenerateCommand())->matches(['generate', '--template=feature.recipe']));
        $this->assertTrue((new PromptGenerateCommand())->matches(['generate', '--multi-step']));
        $this->assertTrue((new GenerateMetricsCommand())->matches(['generate:metrics']));
        $this->assertTrue((new UpgradeCheckCommand())->matches(['upgrade-check']));
        $this->assertTrue((new GraphVisualizeCommand())->matches(['graph', 'visualize']));
        $this->assertTrue((new PromptCommand())->matches(['prompt', 'add', 'feature']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'billing']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'workflow', 'posts']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'orchestration', 'process_doc']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'search', 'posts']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'streams']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'locales']));
        $this->assertTrue((new InspectPlatformCommand())->matches(['inspect', 'roles']));
        $this->assertTrue((new VerifyFeatureCommand())->matches(['verify', 'feature', 'x']));
        $this->assertTrue((new VerifyFeatureWorkCommand())->matches(['verify', 'feature-work', 'x']));
        $this->assertTrue((new VerifyFeaturesCommand())->matches(['verify', 'features']));
        $this->assertTrue((new VerifyArchitectureCommand())->matches(['verify', 'architecture']));
        $this->assertTrue((new VerifyDoneCommand())->matches(['verify', 'done', '--feature=x']));
        $this->assertTrue((new VerifyContextCommand())->matches(['verify', 'context', '--feature=x']));
        $this->assertTrue((new VerifyStateStoreCommand())->matches(['verify', 'state-store']));
        $this->assertTrue((new MarketplaceCommand())->matches(['inspect', 'marketplace']));
        $this->assertTrue((new MarketplaceCommand())->matches(['verify', 'marketplace']));
        $this->assertTrue((new VerifyResourceCommand())->matches(['verify', 'resource', 'posts']));
        $this->assertTrue((new VerifyIntegrationCommand())->matches(['verify', 'notifications']));
        $this->assertTrue((new VerifyIntegrationCommand())->matches(['verify', 'api']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'billing']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'workflows']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'orchestrations']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'search']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'streams']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'locales']));
        $this->assertTrue((new VerifyPlatformCommand())->matches(['verify', 'policies']));
        $this->assertTrue((new VerifyContractsCommand())->matches(['verify', 'contracts']));
        $this->assertTrue((new VerifyContractsCommand())->matches(['verify', 'cli-surface']));
        $this->assertTrue((new VerifyGraphCommand())->matches(['verify', 'graph']));
        $this->assertTrue((new VerifyGraphCommand())->matches(['verify', 'graph-integrity']));
        $this->assertTrue((new VerifyPipelineCommand())->matches(['verify', 'pipeline']));
        $this->assertTrue((new VerifyCompatibilityCommand())->matches(['verify', 'extensions']));
        $this->assertTrue((new VerifyCompatibilityCommand())->matches(['verify', 'compatibility']));
        $this->assertTrue((new ServeCommand())->matches(['serve']));
        $this->assertTrue((new QueueWorkCommand())->matches(['queue:work']));
        $this->assertTrue((new ScheduleRunCommand())->matches(['schedule:run']));
        $this->assertTrue((new ImpactCommand())->matches(['affected-files', 'x']));
        $this->assertTrue((new TestFeatureCommand())->matches(['test', 'feature', 'x']));
        $this->assertTrue((new MigrateDefinitionsCommand())->matches(['migrate', 'definitions', '--dry-run']));
        $this->assertTrue((new CodemodRunCommand())->matches(['codemod', 'run', 'feature-manifest-v1-to-v2', '--dry-run']));
    }
}
